apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-backend
  labels:
    app: {{ .Values.app.name }}-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: FLASK_ENV
          value: {{ .Values.backend.flaskEnv }}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
